language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
env:
    global:
      - secure: "GPzvlio6L76HvuAmV1+qe7IubOGklATKlculio+o8jYwlIb1llBw6zJTEexsy++Z0mGxBk8KO1mmN50b7h8uZyPn3inOD6ubCPvaLAJGFarC0u2/iHt0E9E5OpVShYGMIyIHif61sdtWZA0LRMiUjWuhqpSGvX78J0cu4sXomZs0Oj9PgdWEsre0lw8NggQbHIr0pzrkolEKd9En+Bo1EYjRgzhjRF1fhBV4wY/cSUaZjX2jzFpih2gQyWRdO2UHXGPuSdeDaVpTjR50LuUycsW1JzAp3p6AZnIo6A80erobz0hgBNv1ssn8Acf8zPvJa3IwfwpFvD3/k0sL6fuoYuZ5+Zt9HNUHNqoBkj65OvjNRqcnB1uAF38VcN2VUUXIAK75X59m/7TTP6Y2Iibw8tY+M5vfV18VgzUKIBbWK5xOhlCUoQkBIUhNUsoL3cAVmJmlQtnnaOyBA0xlXIpdW49vNb150Xk6KMtwa7Ey8CYgyObVnqjLNecNjbUKc260XjD8BwTA0sbuCsgOfxLZVEy4yNTBOR0OIc09W+ku3xS4Vl/b3h3rWEy2BYeLQKZ5l3pHJIOYK7vLpBoOiekeFN+aet2NeMMZgOYpq6fjMTQ6pVKffYOsgYdhAl9DHjLCZvd1ixN0/qYUoZB3GIlo5OWfQfEauu33NtikwKj2mH4="

# command to run tests
script:
  - export ALPHA_KEY=$ALPHA_KEY
  - python .travis/make.py
  # - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then python .travis/prtests.py; fi'
deploy:
    provider: pages:git
    token: $GITHUB_TOKEN
    edge: true # opt in to dpl v2
