language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
env:
  global:
  - secure: GPzvlio6L76HvuAmV1+qe7IubOGklATKlculio+o8jYwlIb1llBw6zJTEexsy++Z0mGxBk8KO1mmN50b7h8uZyPn3inOD6ubCPvaLAJGFarC0u2/iHt0E9E5OpVShYGMIyIHif61sdtWZA0LRMiUjWuhqpSGvX78J0cu4sXomZs0Oj9PgdWEsre0lw8NggQbHIr0pzrkolEKd9En+Bo1EYjRgzhjRF1fhBV4wY/cSUaZjX2jzFpih2gQyWRdO2UHXGPuSdeDaVpTjR50LuUycsW1JzAp3p6AZnIo6A80erobz0hgBNv1ssn8Acf8zPvJa3IwfwpFvD3/k0sL6fuoYuZ5+Zt9HNUHNqoBkj65OvjNRqcnB1uAF38VcN2VUUXIAK75X59m/7TTP6Y2Iibw8tY+M5vfV18VgzUKIBbWK5xOhlCUoQkBIUhNUsoL3cAVmJmlQtnnaOyBA0xlXIpdW49vNb150Xk6KMtwa7Ey8CYgyObVnqjLNecNjbUKc260XjD8BwTA0sbuCsgOfxLZVEy4yNTBOR0OIc09W+ku3xS4Vl/b3h3rWEy2BYeLQKZ5l3pHJIOYK7vLpBoOiekeFN+aet2NeMMZgOYpq6fjMTQ6pVKffYOsgYdhAl9DHjLCZvd1ixN0/qYUoZB3GIlo5OWfQfEauu33NtikwKj2mH4=
script:
- export ALPHA_KEY=$ALPHA_KEY
- python .travis/make.py
deploy:
  provider: pages
  api_key:
    secure: jtbghduPQMWr2TvJa+h/LqcdPOWPN+J5mX/Pw05fSgIwjkV3X4/eefa7oAslUaWs5ws7efG3OIeFWa4/7JkvfQ16ulv5Q3+lyyC4Maknbsv/+NyhCbaE7y0wNduJ+v0cK1jbw2Q0djhBd7wFN7iPjqmMs5XyWiHlBevKgiXbGYyFmSGRAt2cokhV+nfHgRrIomO0hxMrWRTe++w6szAScgKIHx4e8s0y7XR3jBTwn3cX0T0t6lc76RyFDgkj77zUohnhX77IK7BcLwGZlVlOfikUQ/qsEZqUnpKveyyHIaywWiO3Pe6f/Thi4kgFWUC1JFQrZk7Sx4Gv/YwUFrKx6BjMSUjR3SYKJteUlYSd464ZhwRM68JPv0xc39CTlU8N2JG2I4eg9Wj7N411lGzYscMSTpVC8+RWUzmIH6nlI2kjng+yIf/N5/hOauv5bRRGHG4qfJICDCjgLHEGVwX4/Mg2Zib6UXlQTwqF3NpRWPaIJs04eNGBL2c9ueOWi3URemcQMZNDylaXONbz/D4JAwqUKbF4KkmA1gCCVMUAPK5pNsE2ADLWAZdQIUA/UhWj94qeNaNKyIUsyilOUivLzvIeoFVS0vR3W6nJLeDQuXexwlM45qMGy+ujHCd4pVq7fB14IWXqmvNkVDO2SpyIHMi34MMn9bTY7fi2DZI7894=
  file: "/Users/joemiller/Desktop/stock-predictor"
  on:
    repo: joemiller4500/stock-predictor
  skip_cleanup: 'true'
